function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 20-Oct-2022 20:05:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create loglog
loglog(X1,Y1,'Marker','o','LineStyle','none');

% Create ylabel
ylabel({'Resistividade aparente (Ωm)'});

% Create xlabel
xlabel({'Espaçamento AB/2 (m)'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XMinorTick','on','XScale','log','YMinorTick','on','YScale','log');
